project_name: runtil
before:
  hooks:
    - go mod tidy
builds:
  - flags:
      - -trimpath
    ldflags:
      - -s # turns off generation of the Go symbol table
      - -w # turns off DWARF debugging information
      - -X github.com/takumakei/runtil/app.Version={{.Version}}
      - -X github.com/takumakei/runtil/app.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: gz
    files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
